<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Authors>daemitus, MidoriKami, foophoof</Authors>
        <Description>Complete your Zodiac relic with style.</Description>
        <PackageProjectUrl>https://github.com/foophoof/ZodiacBuddy</PackageProjectUrl>
        <Version>1.15.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.1.15"/>
        <PackageReference Include="LitJWT" Version="2.0.2"/>
        <PackageReference Include="WrathCombo.API" Version="0.5.4"/>
    </ItemGroup>
</Project>
